### ISSUE TITLE
Connection between MEapp IOS and the STEMapp IOS

### ISSUE THREAD

**Issue by TomForus** [teamforus/concept-identity#5]
**Connection between MEapp IOS and the STEMapp IOS**

## Prerequisites

- Do the IOS version of STEMapp
- Do the IOS version of MEapp

## Description

This issue has been made to create an connection between the MeApp and the StemApp on IOS.

## Functional Design

1. To create an Intent in the MEapp
2. Let the user validate that he or she allows MEapp to make this connection with the STEMapp
3. The STEMapp needs to proces the data from the MEapp into the STEMapp

**User Story:** When you are in the STEMapp you click _'Vote'_. After you click _'Vote'_ the STEMapp sends a request to the MEapp and MEapp sends back the information about voting coins or voting tokens. If there are any. 

## Expected Version

Version 0.1

**Comment by jamalv** [comment]
closing this issue since there currently is no iOS version of the vote app.

**Comment by TomForus** [comment]
Issue has been closed. Will be re-openend when startin of the IOS version of the vote app.
